/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job status and progress */
        get: operations["get_job_api_v1_admin_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange admin credentials for a JWT */
        post: operations["login_api_v1_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query log (filtered, paginated) */
        get: operations["list_queries_api_v1_admin_queries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/queries/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query log as CSV (UTF-8 with BOM) */
        get: operations["export_queries_api_v1_admin_queries_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/queries/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One query with results, answer and feedback */
        get: operations["get_query_api_v1_admin_queries__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a reindex job into a new collection */
        post: operations["reindex_api_v1_admin_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage statistics (defaults to the last 7 days) */
        get: operations["stats_api_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Components, pipeline and index status */
        get: operations["system_api_v1_admin_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Streamed RAG answer with citations (SSE) */
        post: operations["answer_api_v1_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full verbatim article */
        get: operations["get_article_api_v1_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document with its table of contents */
        get: operations["get_document_api_v1_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate a result or an answer (a repeat overwrites) */
        post: operations["feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hybrid / semantic / keyword search over articles */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versions */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerRequest */
        AnswerRequest: {
            /**
             * Context Top K
             * @description How many top articles are given to the generator
             * @default 5
             */
            context_top_k: number;
            filters?: components["schemas"]["SearchFilters"];
            /**
             * Lang
             * @description `auto`: `kk` if the query contains any of ә ғ қ ң ө ұ ү һ і, otherwise `ru`
             * @default auto
             * @enum {string}
             */
            lang: "auto" | "ru" | "kk";
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /**
             * Query
             * @description 1–500 characters after trimming
             * @example Ответственность работодателя за задержку зарплаты
             */
            query: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** AnswerSource */
        AnswerSource: {
            article: components["schemas"]["ArticleRef"];
            doc: components["schemas"]["DocumentRef"];
            /**
             * Ref
             * @description The `n` used in `[n]` citations
             */
            ref: number;
            /** Snippet */
            snippet: string;
        };
        /** AnswerTiming */
        AnswerTiming: {
            /** Search */
            search?: number | null;
            /** Total */
            total?: number | null;
            /** Ttft */
            ttft?: number | null;
        };
        /** ArticleDetail */
        ArticleDetail: {
            /** Amendment Notes */
            amendment_notes?: string[];
            article: components["schemas"]["ArticleRef"];
            doc: components["schemas"]["DocumentRef"];
            /**
             * Lang
             * @enum {string}
             */
            lang: "ru" | "kk";
            /** Next Article Id */
            next_article_id?: string | null;
            /**
             * Parallel Article Id
             * @description The same unit in the other language
             */
            parallel_article_id?: string | null;
            /** Prev Article Id */
            prev_article_id?: string | null;
            /**
             * Text
             * @description Full verbatim article text; line breaks and numbering preserved
             */
            text: string;
        };
        /** ArticleRef */
        ArticleRef: {
            /**
             * Article Id
             * @description `{doc_id}:{lang}:{unit_key}` (data_schema.md §2)
             * @example K1500000414:ru:a113
             */
            article_id: string;
            /** Chapter Title */
            chapter_title?: string | null;
            /** Has Amendments */
            has_amendments: boolean;
            /**
             * Number
             * @example 113
             */
            number?: string | null;
            /** Section Title */
            section_title?: string | null;
            /**
             * Title
             * @example Сроки, место и порядок выплаты заработной платы
             */
            title?: string | null;
            /**
             * Unit Status
             * @enum {string}
             */
            unit_status: "in_force" | "excluded";
            /**
             * Unit Type
             * @enum {string}
             */
            unit_type: "article" | "paragraph" | "chapter" | "preamble" | "annex";
            /**
             * Url
             * @description Article anchor when known, otherwise the document URL
             */
            url: string;
        };
        /** Components */
        Components: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "degraded" | "down" | "unavailable";
            /**
             * Llm
             * @enum {string}
             */
            llm: "ok" | "degraded" | "down" | "unavailable";
            /**
             * Ml Service
             * @enum {string}
             */
            ml_service: "ok" | "degraded" | "down" | "unavailable";
            /**
             * Qdrant
             * @enum {string}
             */
            qdrant: "ok" | "degraded" | "down" | "unavailable";
        };
        /** DocumentDetail */
        DocumentDetail: {
            /**
             * Adopted Date
             * @example 2015-11-23
             */
            adopted_date?: string | null;
            /**
             * Doc Id
             * @description adilet document code
             * @example K1500000414
             */
            doc_id: string;
            /**
             * Doc Type
             * @enum {string}
             */
            doc_type: "code" | "law" | "decree" | "resolution" | "order" | "other";
            /**
             * Number
             * @example 414-V
             */
            number?: string | null;
            /**
             * Revision Date
             * @description Date of the latest amendment in the text
             */
            revision_date?: string | null;
            /**
             * Short Title
             * @example Трудовой кодекс РК
             */
            short_title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_force" | "repealed" | "not_yet_in_force";
            /**
             * Title
             * @example Трудовой кодекс Республики Казахстан
             */
            title: string;
            /**
             * Toc
             * @description Units in document order
             */
            toc: components["schemas"]["TocItem"][];
            /**
             * Url
             * @example https://adilet.zan.kz/rus/docs/K1500000414
             */
            url: string;
        };
        /** DocumentListItem */
        DocumentListItem: {
            /**
             * Adopted Date
             * @example 2015-11-23
             */
            adopted_date?: string | null;
            /** Article Count */
            article_count: number;
            /**
             * Doc Id
             * @description adilet document code
             * @example K1500000414
             */
            doc_id: string;
            /**
             * Doc Type
             * @enum {string}
             */
            doc_type: "code" | "law" | "decree" | "resolution" | "order" | "other";
            /**
             * Number
             * @example 414-V
             */
            number?: string | null;
            /**
             * Revision Date
             * @description Date of the latest amendment in the text
             */
            revision_date?: string | null;
            /**
             * Short Title
             * @example Трудовой кодекс РК
             */
            short_title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_force" | "repealed" | "not_yet_in_force";
            /**
             * Title
             * @example Трудовой кодекс Республики Казахстан
             */
            title: string;
            /**
             * Url
             * @example https://adilet.zan.kz/rus/docs/K1500000414
             */
            url: string;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** DocumentRef */
        DocumentRef: {
            /**
             * Adopted Date
             * @example 2015-11-23
             */
            adopted_date?: string | null;
            /**
             * Doc Id
             * @description adilet document code
             * @example K1500000414
             */
            doc_id: string;
            /**
             * Doc Type
             * @enum {string}
             */
            doc_type: "code" | "law" | "decree" | "resolution" | "order" | "other";
            /**
             * Number
             * @example 414-V
             */
            number?: string | null;
            /**
             * Revision Date
             * @description Date of the latest amendment in the text
             */
            revision_date?: string | null;
            /**
             * Short Title
             * @example Трудовой кодекс РК
             */
            short_title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_force" | "repealed" | "not_yet_in_force";
            /**
             * Title
             * @example Трудовой кодекс Республики Казахстан
             */
            title: string;
            /**
             * Url
             * @example https://adilet.zan.kz/rus/docs/K1500000414
             */
            url: string;
        };
        /**
         * DoneEvent
         * @description `event: done` (sent once, last). `text` is authoritative and replaces the streamed text.
         */
        DoneEvent: {
            /**
             * Answer Id
             * Format: uuid
             */
            answer_id: string;
            /**
             * Citations
             * @description Sorted unique source refs cited in `text`
             */
            citations: number[];
            /**
             * Finish Reason
             * @example stop
             */
            finish_reason: string;
            /** Grounded */
            grounded: boolean;
            /** Invalid Citations Removed */
            invalid_citations_removed: number;
            /**
             * Pipeline Version
             * @default null
             */
            pipeline_version: string | null;
            /** Text */
            text: string;
            timing_ms: components["schemas"]["AnswerTiming"];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @description Machine-readable error code, e.g. `validation_error`
             */
            code: string;
            /**
             * Details
             * @description Extra data, e.g. per-field validation errors
             */
            details?: unknown;
            /**
             * Message
             * @description Human-readable message (English)
             */
            message: string;
            /**
             * Request Id
             * @description Same value as the `X-Request-Id` header
             */
            request_id: string | null;
        };
        /**
         * ErrorEvent
         * @description `event: error` (sent instead of `done` when generation fails after the stream started).
         */
        ErrorEvent: {
            /**
             * Code
             * @description `generation_unavailable` or `internal_error`
             * @example generation_unavailable
             */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FeedbackCounts */
        FeedbackCounts: {
            /** Negative */
            negative: number;
            /** Positive */
            positive: number;
        };
        /** FeedbackItem */
        FeedbackItem: {
            /** Article Id */
            article_id?: string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Rating
             * @enum {integer}
             */
            rating: 1 | -1;
            /**
             * Target
             * @enum {string}
             */
            target: "result" | "answer";
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Article Id
             * @description Required when target=result
             */
            article_id?: string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /**
             * Rating
             * @enum {integer}
             */
            rating: 1 | -1;
            /**
             * Target
             * @enum {string}
             */
            target: "result" | "answer";
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Version */
            app_version: string;
            components: components["schemas"]["Components"];
            /** Pipeline Version */
            pipeline_version?: string | null;
            /**
             * Status
             * @description `ok` (200), `degraded`: search works but a component is down (200), `down`: search cannot work (503)
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
        };
        /** Highlight */
        Highlight: {
            /**
             * End
             * @description Character offset into `snippet` (exclusive)
             */
            end: number;
            /**
             * Start
             * @description Character offset into `snippet` (inclusive)
             */
            start: number;
        };
        /** IndexInfo */
        IndexInfo: {
            /** Alias */
            alias: string;
            /** Articles */
            articles?: number | null;
            /** Collection */
            collection?: string | null;
            /**
             * Compatible
             * @description Collection index_compat_id equals the manifest's; false = reindex required
             */
            compatible: boolean;
            /** Documents */
            documents?: number | null;
            /** Index Compat Id */
            index_compat_id?: string | null;
            last_job?: components["schemas"]["Job"] | null;
            /** Points */
            points?: number | null;
        };
        /** Job */
        Job: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Kind
             * @default reindex
             * @constant
             */
            kind: "reindex";
            /** Message */
            message?: string | null;
            /** Progress */
            progress: number;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
        };
        /** JobRef */
        JobRef: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** PipelineInfo */
        PipelineInfo: {
            /** Embedder */
            embedder?: string | null;
            /** Generator */
            generator?: string | null;
            /** Index Compat Id */
            index_compat_id?: string | null;
            /** Pipeline Version */
            pipeline_version?: string | null;
            /** Reranker */
            reranker?: string | null;
        };
        /** QueryCount */
        QueryCount: {
            /** Count */
            count: number;
            /**
             * Query
             * @description Normalised query (lower-cased, whitespace-collapsed)
             */
            query: string;
        };
        /** QueryLogAnswer */
        QueryLogAnswer: {
            /**
             * Answer Id
             * Format: uuid
             */
            answer_id: string;
            /** Citations */
            citations: number[];
            /** Grounded */
            grounded: boolean;
            /** Text */
            text: string;
            timing_ms: components["schemas"]["AnswerTiming"];
        };
        /** QueryLogDetail */
        QueryLogDetail: {
            answer?: components["schemas"]["QueryLogAnswer"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Degraded */
            degraded?: ("rerank" | "semantic" | "generation")[];
            feedback: components["schemas"]["FeedbackCounts"];
            /** Feedback Items */
            feedback_items: components["schemas"]["FeedbackItem"][];
            filters: components["schemas"]["SearchFilters"];
            /** Has Answer */
            has_answer: boolean;
            /**
             * Lang
             * @enum {string}
             */
            lang: "ru" | "kk";
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /** Pipeline Version */
            pipeline_version?: string | null;
            /** Query */
            query: string;
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** Result Count */
            result_count: number;
            /** Results */
            results: components["schemas"]["QueryLogResult"][];
            /** Search Ms */
            search_ms?: number | null;
            /** Session Hash */
            session_hash?: string | null;
            timing_ms: components["schemas"]["SearchTiming"];
            /** Top Article Id */
            top_article_id?: string | null;
            /** Top K */
            top_k: number;
        };
        /** QueryLogItem */
        QueryLogItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Degraded */
            degraded?: ("rerank" | "semantic" | "generation")[];
            feedback: components["schemas"]["FeedbackCounts"];
            /** Has Answer */
            has_answer: boolean;
            /**
             * Lang
             * @enum {string}
             */
            lang: "ru" | "kk";
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /** Query */
            query: string;
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** Result Count */
            result_count: number;
            /** Search Ms */
            search_ms?: number | null;
            /** Top Article Id */
            top_article_id?: string | null;
        };
        /** QueryLogPage */
        QueryLogPage: {
            /** Items */
            items: components["schemas"]["QueryLogItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** QueryLogResult */
        QueryLogResult: {
            /** Article Id */
            article_id: string;
            /** Doc Short Title */
            doc_short_title?: string | null;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** Title */
            title?: string | null;
        };
        /** ReindexRequest */
        ReindexRequest: {
            /**
             * Source
             * @default processed
             * @enum {string}
             */
            source: "processed" | "sample";
            /**
             * Use Precomputed Embeddings
             * @default true
             */
            use_precomputed_embeddings: boolean;
        };
        /** SearchFilters */
        SearchFilters: {
            /**
             * Date From
             * @description Act adoption date, inclusive
             */
            date_from?: string | null;
            /**
             * Date To
             * @description Act adoption date, inclusive
             */
            date_to?: string | null;
            /**
             * Doc Ids
             * @description Empty = no filter
             */
            doc_ids?: string[];
            /**
             * Doc Types
             * @description Empty = no filter
             */
            doc_types?: ("code" | "law" | "decree" | "resolution" | "order" | "other")[];
            /**
             * In Force Only
             * @description Act in force **and** article not excluded
             * @default true
             */
            in_force_only: boolean;
        };
        /** SearchRequest */
        SearchRequest: {
            filters?: components["schemas"]["SearchFilters"];
            /**
             * Lang
             * @description `auto`: `kk` if the query contains any of ә ғ қ ң ө ұ ү һ і, otherwise `ru`
             * @default auto
             * @enum {string}
             */
            lang: "auto" | "ru" | "kk";
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /**
             * Query
             * @description 1–500 characters after trimming
             * @example Ответственность работодателя за задержку зарплаты
             */
            query: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Degraded */
            degraded?: ("rerank" | "semantic" | "generation")[];
            /**
             * Lang
             * @description The resolved language
             * @enum {string}
             */
            lang: "ru" | "kk";
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /** Pipeline Version */
            pipeline_version?: string | null;
            /** Query */
            query: string;
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /**
             * Results
             * @description One result per article; may be empty
             */
            results: components["schemas"]["SearchResult"][];
            timing_ms: components["schemas"]["SearchTiming"];
            /** Total Candidates */
            total_candidates: number;
        };
        /** SearchResult */
        SearchResult: {
            article: components["schemas"]["ArticleRef"];
            /**
             * Chunk Id
             * @example K1500000414:ru:a113:c0
             */
            chunk_id: string;
            doc: components["schemas"]["DocumentRef"];
            /** Highlights */
            highlights?: components["schemas"]["Highlight"][];
            /**
             * Lang
             * @enum {string}
             */
            lang: "ru" | "kk";
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /**
             * Score Type
             * @enum {string}
             */
            score_type: "rerank" | "fusion" | "fts";
            /**
             * Snippet
             * @description Best passage of the best chunk
             */
            snippet: string;
        };
        /**
         * SearchTiming
         * @description Milliseconds per stage. A key is present only if its stage ran.
         */
        SearchTiming: {
            /** Embed */
            embed?: number;
            /** Fuse */
            fuse?: number;
            /** Rerank */
            rerank?: number;
            /** Retrieve */
            retrieve?: number;
            /** Total */
            total?: number;
        };
        /**
         * SourcesEvent
         * @description `event: sources` (sent once, first).
         */
        SourcesEvent: {
            /** Degraded */
            degraded?: ("rerank" | "semantic" | "generation")[];
            /**
             * Lang
             * @enum {string}
             */
            lang: "ru" | "kk";
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** Sources */
            sources: components["schemas"]["AnswerSource"][];
        };
        /** StatsDay */
        StatsDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Queries */
            queries: number;
            /** Search P95 Ms */
            search_p95_ms?: number | null;
            /** Zero Result Rate */
            zero_result_rate?: number | null;
        };
        /** StatsLang */
        StatsLang: {
            /**
             * Lang
             * @enum {string}
             */
            lang: "ru" | "kk";
            /** Queries */
            queries: number;
        };
        /** StatsLatency */
        StatsLatency: {
            /** Answer Ttft P50 */
            answer_ttft_p50?: number | null;
            /** Answer Ttft P95 */
            answer_ttft_p95?: number | null;
            /** Search P50 */
            search_p50?: number | null;
            /** Search P95 */
            search_p95?: number | null;
        };
        /** StatsMode */
        StatsMode: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /** Queries */
            queries: number;
        };
        /** StatsRates */
        StatsRates: {
            /** Degraded Rate */
            degraded_rate?: number | null;
            /**
             * Satisfaction Rate
             * @description positive / (positive + negative); null without feedback
             */
            satisfaction_rate?: number | null;
            /** Zero Result Rate */
            zero_result_rate?: number | null;
        };
        /** StatsResponse */
        StatsResponse: {
            /** By Day */
            by_day: components["schemas"]["StatsDay"][];
            /** By Lang */
            by_lang: components["schemas"]["StatsLang"][];
            /** By Mode */
            by_mode: components["schemas"]["StatsMode"][];
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            latency_ms: components["schemas"]["StatsLatency"];
            rates: components["schemas"]["StatsRates"];
            /** Top Queries */
            top_queries: components["schemas"]["QueryCount"][];
            /** Top Zero Result Queries */
            top_zero_result_queries: components["schemas"]["QueryCount"][];
            totals: components["schemas"]["StatsTotals"];
        };
        /** StatsTotals */
        StatsTotals: {
            /** Answers */
            answers: number;
            /** Feedback Negative */
            feedback_negative: number;
            /** Feedback Positive */
            feedback_positive: number;
            /** Queries */
            queries: number;
            /** Unique Sessions */
            unique_sessions: number;
            /** Zero Result Queries */
            zero_result_queries: number;
        };
        /** SystemResponse */
        SystemResponse: {
            /** App Version */
            app_version: string;
            components: components["schemas"]["Components"];
            /** Git Sha */
            git_sha: string;
            index: components["schemas"]["IndexInfo"];
            pipeline: components["schemas"]["PipelineInfo"];
            /** Uptime S */
            uptime_s: number;
        };
        /** TocItem */
        TocItem: {
            /**
             * Article Id
             * @description `{doc_id}:{lang}:{unit_key}` (data_schema.md §2)
             * @example K1500000414:ru:a113
             */
            article_id: string;
            /** Chapter Title */
            chapter_title?: string | null;
            /** Number */
            number?: string | null;
            /** Section Title */
            section_title?: string | null;
            /** Title */
            title?: string | null;
            /**
             * Unit Status
             * @enum {string}
             */
            unit_status: "in_force" | "excluded";
            /**
             * Unit Type
             * @enum {string}
             */
            unit_type: "article" | "paragraph" | "chapter" | "preamble" | "annex";
        };
        /**
         * TokenEvent
         * @description `event: token` (sent many times).
         */
        TokenEvent: {
            /** Text */
            text: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires In
             * @description Seconds until the token expires
             * @example 28800
             */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** VersionResponse */
        VersionResponse: {
            /** App Version */
            app_version: string;
            /** Git Sha */
            git_sha: string;
            /**
             * Index Collection
             * @description The collection the `legal_chunks` alias points to
             */
            index_collection?: string | null;
            /** Pipeline Version */
            pipeline_version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_job_api_v1_admin_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented yet (stub) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_api_v1_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (see the `Retry-After` header) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented yet (stub) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_queries_api_v1_admin_queries_get: {
        parameters: {
            query?: {
                /** @description Substring of the query */
                q?: string | null;
                lang?: ("ru" | "kk") | null;
                mode?: ("hybrid" | "semantic" | "keyword") | null;
                zero_results?: boolean | null;
                feedback?: ("positive" | "negative") | null;
                degraded?: boolean | null;
                date_from?: string | null;
                date_to?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryLogPage"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented yet (stub) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_queries_api_v1_admin_queries_export_get: {
        parameters: {
            query?: {
                /** @description Substring of the query */
                q?: string | null;
                lang?: ("ru" | "kk") | null;
                mode?: ("hybrid" | "semantic" | "keyword") | null;
                zero_results?: boolean | null;
                feedback?: ("positive" | "negative") | null;
                degraded?: boolean | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per query. Columns: query_id, created_at, query, lang, mode, result_count, top_article_id, search_ms, has_answer, feedback_positive, feedback_negative, degraded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented yet (stub) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_query_api_v1_admin_queries__query_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryLogDetail"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented yet (stub) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reindex_api_v1_admin_reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReindexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRef"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented yet (stub) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stats_api_v1_admin_stats_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented yet (stub) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    system_api_v1_admin_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not implemented yet (stub) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    answer_api_v1_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /**
             * @description Server-Sent Events stream. Event order: `sources` (once) → `token` (many) → `done` (once),
             *     or `error` instead of `done` if generation fails after the stream started.
             *     The JSON in each event's `data:` line follows the schema named in `x-sse-events`
             *     (`SourcesEvent`, `TokenEvent`, `DoneEvent`, `ErrorEvent`). A `: ping` comment is sent every 15 s.
             *     `done.text` is authoritative: replace the streamed text with it.
             *     Errors before the stream starts (validation, search unavailable) are normal JSON responses.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (see the `Retry-After` header) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required upstream component is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_article_api_v1_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query: {
                lang: "ru" | "kk";
                doc_type?: ("code" | "law" | "decree" | "resolution" | "order" | "other") | null;
                /** @description Substring of the title */
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_document_api_v1_documents__doc_id__get: {
        parameters: {
            query: {
                lang: "ru" | "kk";
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Search cannot work (`down`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (see the `Retry-After` header) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required upstream component is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
