"""Alembic on a real Postgres: upgrade, downgrade, re-upgrade, no drift, DB constraints."""

import asyncio
import uuid
from collections.abc import Awaitable, Callable, Iterator
from typing import Any

import asyncpg
import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from tests.integration.conftest import plain_dsn

pytestmark = pytest.mark.integration

TABLES = {
    "documents",
    "articles",
    "query_logs",
    "answers",
    "feedback",
    "index_jobs",
    "index_state",
    "admin_users",
}


def run_sql(url: str, fn: Callable[[asyncpg.Connection], Awaitable[Any]]) -> Any:
    async def go() -> Any:
        conn = await asyncpg.connect(plain_dsn(url))
        try:
            return await fn(conn)
        finally:
            await conn.close()

    return asyncio.run(go())


def tables(url: str) -> set[str]:
    rows = run_sql(
        url,
        lambda c: c.fetch("SELECT tablename FROM pg_tables WHERE schemaname = 'public'"),
    )
    return {row["tablename"] for row in rows} - {"alembic_version"}


@pytest.fixture
def migrated(alembic_config: Config, database_url: str) -> Iterator[str]:
    command.downgrade(alembic_config, "base")
    command.upgrade(alembic_config, "head")
    yield database_url
    command.downgrade(alembic_config, "base")


def test_upgrade_downgrade_upgrade(alembic_config: Config, database_url: str) -> None:
    command.downgrade(alembic_config, "base")
    assert tables(database_url) == set()
    command.upgrade(alembic_config, "head")
    assert tables(database_url) == TABLES
    command.downgrade(alembic_config, "base")
    assert tables(database_url) == set()
    command.upgrade(alembic_config, "head")
    assert tables(database_url) == TABLES


def test_models_match_migrations(migrated: str, alembic_config: Config) -> None:
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"models and migrations differ; add a migration:\n{exc}")


async def _insert_article(conn: asyncpg.Connection, lang: str, title: str, text: str) -> None:
    await conn.execute(
        """INSERT INTO documents (doc_id, lang, title, short_title, doc_type, status, source_url,
                                  corpus_version)
           VALUES ('K1500000414', $1, 'Трудовой кодекс', 'ТК РК', 'code', 'in_force', 'u', 'v')
           ON CONFLICT DO NOTHING""",
        lang,
    )
    await conn.execute(
        """INSERT INTO articles (article_id, doc_id, lang, unit_type, unit_key, unit_order,
                                 unit_status, unit_title, text, source_url, content_hash,
                                 corpus_version)
           VALUES ($1, 'K1500000414', $2, 'article', 'a113', 0, 'in_force', $3, $4,
                   'u', 'h', 'v')""",
        f"K1500000414:{lang}:a113",
        lang,
        title,
        text,
    )


def test_russian_full_text_uses_stemming(migrated: str) -> None:
    async def check(conn: asyncpg.Connection) -> Any:
        await _insert_article(
            conn, "ru", "Сроки выплаты заработной платы", "Работодатель выплачивает зарплату."
        )
        return await conn.fetchval(
            """SELECT count(*) FROM articles
               WHERE tsv @@ websearch_to_tsquery('russian', 'выплаты заработных плат')"""
        )

    assert run_sql(migrated, check) == 1


def test_kazakh_full_text_uses_simple_config(migrated: str) -> None:
    async def check(conn: asyncpg.Connection) -> Any:
        await _insert_article(conn, "kk", "Жалақы төлеу мерзімдері", "Жұмыс беруші жалақы төлейді.")
        return await conn.fetchval(
            "SELECT count(*) FROM articles WHERE tsv @@ websearch_to_tsquery('simple', 'жалақы')"
        )

    assert run_sql(migrated, check) == 1


def test_only_one_active_index_job(migrated: str) -> None:
    async def check(conn: asyncpg.Connection) -> None:
        await conn.execute(
            "INSERT INTO index_jobs (job_id, status) VALUES ($1, 'succeeded')", uuid.uuid4()
        )
        await conn.execute(
            "INSERT INTO index_jobs (job_id, status) VALUES ($1, 'running')", uuid.uuid4()
        )
        with pytest.raises(asyncpg.UniqueViolationError):
            await conn.execute("INSERT INTO index_jobs (job_id) VALUES ($1)", uuid.uuid4())

    run_sql(migrated, check)


def test_feedback_upsert_key_treats_nulls_as_equal(migrated: str) -> None:
    query_id = uuid.uuid4()

    async def check(conn: asyncpg.Connection) -> Any:
        await conn.execute(
            """INSERT INTO query_logs (query_id, query, query_norm, lang, mode, top_k)
               VALUES ($1, 'q', 'q', 'ru', 'hybrid', 10)""",
            query_id,
        )
        upsert = """INSERT INTO feedback (query_id, session_hash, target, article_id, rating)
                    VALUES ($1, NULL, 'answer', NULL, $2)
                    ON CONFLICT ON CONSTRAINT uq_feedback_session_query_target_article
                    DO UPDATE SET rating = EXCLUDED.rating"""
        await conn.execute(upsert, query_id, 1)
        await conn.execute(upsert, query_id, -1)
        return await conn.fetch("SELECT rating FROM feedback WHERE query_id = $1", query_id)

    rows = run_sql(migrated, check)
    assert [row["rating"] for row in rows] == [-1]


def test_check_constraints(migrated: str) -> None:
    query_id = uuid.uuid4()

    async def check(conn: asyncpg.Connection) -> None:
        with pytest.raises(asyncpg.CheckViolationError):
            await conn.execute(
                """INSERT INTO query_logs (query_id, query, query_norm, lang, mode, top_k)
                   VALUES ($1, 'q', 'q', 'kz', 'hybrid', 10)""",
                query_id,
            )
        await conn.execute(
            """INSERT INTO query_logs (query_id, query, query_norm, lang, mode, top_k, degraded)
               VALUES ($1, 'q', 'q', 'ru', 'hybrid', 10, ARRAY['semantic'])""",
            query_id,
        )
        assert await conn.fetchval(
            "SELECT is_degraded FROM query_logs WHERE query_id = $1", query_id
        )
        with pytest.raises(asyncpg.CheckViolationError):
            await conn.execute(
                """INSERT INTO feedback (query_id, target, rating) VALUES ($1, 'result', 1)""",
                query_id,
            )

    run_sql(migrated, check)
